In [1]:
from sklearn.datasets import load_wine
import pandas as pd
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

C:\Users\82109\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
data = load_wine()
data

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [4]:
data_data = pd.DataFrame(data.data, columns = data.feature_names)
data_label = pd.DataFrame(data.target, columns = ['label'])
data=pd.concat([data_data,data_label],axis=1)
data

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  label  
0                            3.92   1065.0      0  
1                            3.40   1050.0      0  
2                            3.17   1185.0      0  
3                            3.45   1480.0      0  
4                            2.93    735.0      0  
..                            ...      ...    ...  
173                          1.74    740.0      2  
174                          1.56    750.0      2  
175                          1.56    835.0      2  
176                          1.62    840.0      2  
177                          1.60    560.0      2  

[178 rows x 14 columns]

In [5]:
#Splitting the data into training and test test
X = data.iloc[:,0:13].values
y = data.iloc[:,13].values


from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 

In [6]:
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [7]:
#특성 스케일링
from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()
scaler.fit(X_train)
StandardScaler()
StandardScaler()
scaled_X_train= scaler.transform(X_train)
scaled_X_test= scaler.transform(X_test)

In [8]:
Y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1,

In [9]:
#Defining the model 

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam


model = Sequential()

model.add(Dense(100,input_shape=(13,),activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(50,activation='relu'))
model.add(Dense(3,activation='softmax'))

model.compile(Adam(lr=0.04),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 100)               1400      
                                                                 
 dense_1 (Dense)             (None, 10)                1010      
                                                                 
 dense_2 (Dense)             (None, 50)                550       
                                                                 
 dense_3 (Dense)             (None, 3)                 153       
                                                                 
Total params: 3,113
Trainable params: 3,113
Non-trainable params: 0
_________________________________________________________________


C:\Users\82109\anaconda3\lib\site-packages\keras\optimizers\legacy\adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [10]:
#fitting the model and predicting 

# fit network
model_history=model.fit(x=X_train, y=y_train, epochs=100, batch_size=32,validation_data= (X_test,y_test))

y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/100
5/5 [==============================] - 1s 59ms/step - loss: 38.6304 - accuracy: 0.3239 - val_loss: 1.1872 - val_accuracy: 0.1667
Epoch 2/100
5/5 [==============================] - 0s 9ms/step - loss: 1.1095 - accuracy: 0.3521 - val_loss: 1.0564 - val_accuracy: 0.4444
Epoch 3/100
5/5 [==============================] - 0s 10ms/step - loss: 1.0967 - accuracy: 0.3873 - val_loss: 1.0577 - val_accuracy: 0.4444
Epoch 4/100
5/5 [==============================] - 0s 11ms/step - loss: 1.0964 - accuracy: 0.3873 - val_loss: 1.0572 - val_accuracy: 0.4444
Epoch 5/100
5/5 [==============================] - 0s 10ms/step - loss: 1.0941 - accuracy: 0.3873 - val_loss: 1.0641 - val_accuracy: 0.4444
Epoch 6/100
5/5 [==============================] - 0s 9ms/step - loss: 1.0949 - accuracy: 0.3873 - val_loss: 1.0711 - val_accuracy: 0.4444
Epoch 7/100
5/5 [==============================] - 0s 10ms/step - loss: 1.0929 - accuracy: 0.3873 - val_loss: 1.0797 - val_accuracy: 0.4444
Epoch 8/100
5/5 [====

5/5 [==============================] - 0s 10ms/step - loss: 1.0927 - accuracy: 0.3873 - val_loss: 1.0673 - val_accuracy: 0.4444
Epoch 60/100
5/5 [==============================] - 0s 10ms/step - loss: 1.0922 - accuracy: 0.3873 - val_loss: 1.0707 - val_accuracy: 0.4444
Epoch 61/100
5/5 [==============================] - 0s 12ms/step - loss: 1.0927 - accuracy: 0.3873 - val_loss: 1.0714 - val_accuracy: 0.4444
Epoch 62/100
5/5 [==============================] - 0s 11ms/step - loss: 1.0926 - accuracy: 0.3873 - val_loss: 1.0646 - val_accuracy: 0.4444
Epoch 63/100
5/5 [==============================] - 0s 10ms/step - loss: 1.0932 - accuracy: 0.3873 - val_loss: 1.0651 - val_accuracy: 0.4444
Epoch 64/100
5/5 [==============================] - 0s 11ms/step - loss: 1.0932 - accuracy: 0.3873 - val_loss: 1.0709 - val_accuracy: 0.4444
Epoch 65/100
5/5 [==============================] - 0s 11ms/step - loss: 1.0933 - accuracy: 0.3873 - val_loss: 1.0769 - val_accuracy: 0.4444
Epoch 66/100
5/5 [========

In [11]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        14
           1       0.44      1.00      0.62        16
           2       0.00      0.00      0.00         6

    accuracy                           0.44        36
   macro avg       0.15      0.33      0.21        36
weighted avg       0.20      0.44      0.27        36

[[ 0 14  0]
 [ 0 16  0]
 [ 0  6  0]]


C:\Users\82109\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\82109\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\82109\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [12]:
#Defining the model 

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD,Adam
from keras.layers import Input, Dense
from keras.models import Model

# 이는 텐서를 반환합니다
inputs = Input(shape=(13,))
x = Dense(10, activation='relu')(inputs)
x2 = Dense(8, activation='relu')(x)
x3 = Dense(6, activation='relu')(x2)
output=Dense(2,activation='softmax')(x3)

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 100)               1400      
                                                                 
 dense_1 (Dense)             (None, 10)                1010      
                                                                 
 dense_2 (Dense)             (None, 50)                550       
                                                                 
 dense_3 (Dense)             (None, 3)                 153       
                                                                 
Total params: 3,113
Trainable params: 3,113
Non-trainable params: 0
_________________________________________________________________


In [13]:
#fitting the model and predicting 

# fit network
model_history=model.fit(x=X_train, y=y_train, epochs=100, batch_size=32,validation_data= (X_test,y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/100
5/5 [==============================] - 0s 22ms/step - loss: 1.0944 - accuracy: 0.3873 - val_loss: 1.0784 - val_accuracy: 0.4444
Epoch 2/100
5/5 [==============================] - 0s 13ms/step - loss: 1.0923 - accuracy: 0.3873 - val_loss: 1.0664 - val_accuracy: 0.4444
Epoch 3/100
5/5 [==============================] - 0s 13ms/step - loss: 1.0947 - accuracy: 0.3873 - val_loss: 1.0592 - val_accuracy: 0.4444
Epoch 4/100
5/5 [==============================] - 0s 10ms/step - loss: 1.0945 - accuracy: 0.3873 - val_loss: 1.0640 - val_accuracy: 0.4444
Epoch 5/100
5/5 [==============================] - 0s 9ms/step - loss: 1.0931 - accuracy: 0.3873 - val_loss: 1.0650 - val_accuracy: 0.4444
Epoch 6/100
5/5 [==============================] - 0s 10ms/step - loss: 1.0949 - accuracy: 0.3873 - val_loss: 1.0740 - val_accuracy: 0.4444
Epoch 7/100
5/5 [==============================] - 0s 10ms/step - loss: 1.0925 - accuracy: 0.3873 - val_loss: 1.0739 - val_accuracy: 0.4444
Epoch 8/100
5/5 [====

5/5 [==============================] - 0s 9ms/step - loss: 1.0952 - accuracy: 0.3873 - val_loss: 1.0616 - val_accuracy: 0.4444
Epoch 60/100
5/5 [==============================] - 0s 10ms/step - loss: 1.0924 - accuracy: 0.3873 - val_loss: 1.0679 - val_accuracy: 0.4444
Epoch 61/100
5/5 [==============================] - 0s 10ms/step - loss: 1.0922 - accuracy: 0.3873 - val_loss: 1.0812 - val_accuracy: 0.4444
Epoch 62/100
5/5 [==============================] - 0s 11ms/step - loss: 1.0965 - accuracy: 0.3873 - val_loss: 1.0937 - val_accuracy: 0.4444
Epoch 63/100
5/5 [==============================] - 0s 9ms/step - loss: 1.0952 - accuracy: 0.3873 - val_loss: 1.0813 - val_accuracy: 0.4444
Epoch 64/100
5/5 [==============================] - 0s 10ms/step - loss: 1.0931 - accuracy: 0.3873 - val_loss: 1.0728 - val_accuracy: 0.4444
Epoch 65/100
5/5 [==============================] - 0s 12ms/step - loss: 1.0925 - accuracy: 0.3873 - val_loss: 1.0688 - val_accuracy: 0.4444
Epoch 66/100
5/5 [==========

In [14]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        14
           1       0.44      1.00      0.62        16
           2       0.00      0.00      0.00         6

    accuracy                           0.44        36
   macro avg       0.15      0.33      0.21        36
weighted avg       0.20      0.44      0.27        36

[[ 0 14  0]
 [ 0 16  0]
 [ 0  6  0]]


C:\Users\82109\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\82109\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\82109\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
